# Generated by Django 3.0.6 on 2020-05-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='article title')),
                ('text', models.TextField(verbose_name='article text')),
                ('author_name', models.CharField(max_length=50, verbose_name='article author name')),
                ('pub_date', models.DateTimeField(verbose_name='article publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='comment title')),
                ('text', models.TextField(verbose_name='comment text')),
                ('author_name', models.CharField(max_length=50, verbose_name='comment author name')),
                ('pub_date', models.DateTimeField(verbose_name='comment publication date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
